--
-- PostgreSQL database dump
--

-- Dumped from database version 15.12 (Debian 15.12-1.pgdg120+1)
-- Dumped by pg_dump version 15.12 (Debian 15.12-1.pgdg120+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: authtoken_token; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.authtoken_token (
    key character varying(40) NOT NULL,
    created timestamp with time zone NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.authtoken_token OWNER TO postgres;

--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- Name: services_deliverylog; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.services_deliverylog (
    id bigint NOT NULL,
    status character varying(20) NOT NULL,
    notes text,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    delivery_user_id bigint,
    order_id bigint NOT NULL
);


ALTER TABLE public.services_deliverylog OWNER TO postgres;

--
-- Name: services_deliverylog_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.services_deliverylog ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.services_deliverylog_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: services_invoice; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.services_invoice (
    id bigint NOT NULL,
    total_amount numeric(10,2) NOT NULL,
    status character varying(20) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    user_id bigint NOT NULL,
    order_id bigint NOT NULL
);


ALTER TABLE public.services_invoice OWNER TO postgres;

--
-- Name: services_invoice_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.services_invoice ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.services_invoice_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: services_invoiceitem; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.services_invoiceitem (
    id bigint NOT NULL,
    product_name character varying(100) NOT NULL,
    quantity integer NOT NULL,
    unit_price numeric(10,2) NOT NULL,
    subtotal numeric(10,2) NOT NULL,
    invoice_id bigint NOT NULL,
    CONSTRAINT services_invoiceitem_quantity_check CHECK ((quantity >= 0))
);


ALTER TABLE public.services_invoiceitem OWNER TO postgres;

--
-- Name: services_invoiceitem_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.services_invoiceitem ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.services_invoiceitem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: services_kitchenlog; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.services_kitchenlog (
    id bigint NOT NULL,
    action character varying(20) NOT NULL,
    notes text,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    order_id bigint NOT NULL
);


ALTER TABLE public.services_kitchenlog OWNER TO postgres;

--
-- Name: services_kitchenlog_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.services_kitchenlog ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.services_kitchenlog_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: services_menuitem; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.services_menuitem (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    description text NOT NULL,
    category character varying(20) NOT NULL,
    price numeric(10,2) NOT NULL,
    available boolean NOT NULL
);


ALTER TABLE public.services_menuitem OWNER TO postgres;

--
-- Name: services_menuitem_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.services_menuitem ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.services_menuitem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: services_order; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.services_order (
    id bigint NOT NULL,
    status character varying(20) NOT NULL,
    order_type character varying(20) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.services_order OWNER TO postgres;

--
-- Name: services_order_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.services_order ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.services_order_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: services_orderitem; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.services_orderitem (
    id bigint NOT NULL,
    quantity integer NOT NULL,
    notes text,
    order_id bigint NOT NULL,
    product_id bigint NOT NULL,
    CONSTRAINT services_orderitem_quantity_check CHECK ((quantity >= 0))
);


ALTER TABLE public.services_orderitem OWNER TO postgres;

--
-- Name: services_orderitem_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.services_orderitem ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.services_orderitem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: services_profile; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.services_profile (
    id bigint NOT NULL,
    address text,
    lat double precision,
    lng double precision,
    user_id bigint NOT NULL
);


ALTER TABLE public.services_profile OWNER TO postgres;

--
-- Name: services_profile_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.services_profile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.services_profile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: services_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.services_user (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    email character varying(254) NOT NULL,
    role character varying(20)
);


ALTER TABLE public.services_user OWNER TO postgres;

--
-- Name: services_user_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.services_user_groups (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.services_user_groups OWNER TO postgres;

--
-- Name: services_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.services_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.services_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: services_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.services_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.services_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: services_user_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.services_user_user_permissions (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.services_user_user_permissions OWNER TO postgres;

--
-- Name: services_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.services_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.services_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: authtoken_token authtoken_token_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_pkey PRIMARY KEY (key);


--
-- Name: authtoken_token authtoken_token_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_user_id_key UNIQUE (user_id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: services_deliverylog services_deliverylog_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.services_deliverylog
    ADD CONSTRAINT services_deliverylog_pkey PRIMARY KEY (id);


--
-- Name: services_invoice services_invoice_order_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.services_invoice
    ADD CONSTRAINT services_invoice_order_id_key UNIQUE (order_id);


--
-- Name: services_invoice services_invoice_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.services_invoice
    ADD CONSTRAINT services_invoice_pkey PRIMARY KEY (id);


--
-- Name: services_invoiceitem services_invoiceitem_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.services_invoiceitem
    ADD CONSTRAINT services_invoiceitem_pkey PRIMARY KEY (id);


--
-- Name: services_kitchenlog services_kitchenlog_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.services_kitchenlog
    ADD CONSTRAINT services_kitchenlog_pkey PRIMARY KEY (id);


--
-- Name: services_menuitem services_menuitem_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.services_menuitem
    ADD CONSTRAINT services_menuitem_pkey PRIMARY KEY (id);


--
-- Name: services_order services_order_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.services_order
    ADD CONSTRAINT services_order_pkey PRIMARY KEY (id);


--
-- Name: services_orderitem services_orderitem_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.services_orderitem
    ADD CONSTRAINT services_orderitem_pkey PRIMARY KEY (id);


--
-- Name: services_profile services_profile_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.services_profile
    ADD CONSTRAINT services_profile_pkey PRIMARY KEY (id);


--
-- Name: services_profile services_profile_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.services_profile
    ADD CONSTRAINT services_profile_user_id_key UNIQUE (user_id);


--
-- Name: services_user services_user_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.services_user
    ADD CONSTRAINT services_user_email_key UNIQUE (email);


--
-- Name: services_user_groups services_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.services_user_groups
    ADD CONSTRAINT services_user_groups_pkey PRIMARY KEY (id);


--
-- Name: services_user_groups services_user_groups_user_id_group_id_71946014_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.services_user_groups
    ADD CONSTRAINT services_user_groups_user_id_group_id_71946014_uniq UNIQUE (user_id, group_id);


--
-- Name: services_user services_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.services_user
    ADD CONSTRAINT services_user_pkey PRIMARY KEY (id);


--
-- Name: services_user_user_permissions services_user_user_permi_user_id_permission_id_6a7226ee_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.services_user_user_permissions
    ADD CONSTRAINT services_user_user_permi_user_id_permission_id_6a7226ee_uniq UNIQUE (user_id, permission_id);


--
-- Name: services_user_user_permissions services_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.services_user_user_permissions
    ADD CONSTRAINT services_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: authtoken_token_key_10f0b77e_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX authtoken_token_key_10f0b77e_like ON public.authtoken_token USING btree (key varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: services_deliverylog_delivery_user_id_eb6d4217; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX services_deliverylog_delivery_user_id_eb6d4217 ON public.services_deliverylog USING btree (delivery_user_id);


--
-- Name: services_deliverylog_order_id_26f6bb2d; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX services_deliverylog_order_id_26f6bb2d ON public.services_deliverylog USING btree (order_id);


--
-- Name: services_invoice_user_id_7bbf1d33; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX services_invoice_user_id_7bbf1d33 ON public.services_invoice USING btree (user_id);


--
-- Name: services_invoiceitem_invoice_id_1c5e78ec; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX services_invoiceitem_invoice_id_1c5e78ec ON public.services_invoiceitem USING btree (invoice_id);


--
-- Name: services_kitchenlog_order_id_45b5526d; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX services_kitchenlog_order_id_45b5526d ON public.services_kitchenlog USING btree (order_id);


--
-- Name: services_order_user_id_2651f880; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX services_order_user_id_2651f880 ON public.services_order USING btree (user_id);


--
-- Name: services_orderitem_order_id_3d4c1ac5; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX services_orderitem_order_id_3d4c1ac5 ON public.services_orderitem USING btree (order_id);


--
-- Name: services_orderitem_product_id_f8c5c801; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX services_orderitem_product_id_f8c5c801 ON public.services_orderitem USING btree (product_id);


--
-- Name: services_user_email_a692fefa_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX services_user_email_a692fefa_like ON public.services_user USING btree (email varchar_pattern_ops);


--
-- Name: services_user_groups_group_id_7a938d90; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX services_user_groups_group_id_7a938d90 ON public.services_user_groups USING btree (group_id);


--
-- Name: services_user_groups_user_id_de285bf3; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX services_user_groups_user_id_de285bf3 ON public.services_user_groups USING btree (user_id);


--
-- Name: services_user_user_permissions_permission_id_95d2c36c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX services_user_user_permissions_permission_id_95d2c36c ON public.services_user_user_permissions USING btree (permission_id);


--
-- Name: services_user_user_permissions_user_id_45836c48; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX services_user_user_permissions_user_id_45836c48 ON public.services_user_user_permissions USING btree (user_id);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: authtoken_token authtoken_token_user_id_35299eff_fk_services_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_user_id_35299eff_fk_services_user_id FOREIGN KEY (user_id) REFERENCES public.services_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_services_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_services_user_id FOREIGN KEY (user_id) REFERENCES public.services_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: services_deliverylog services_deliverylog_delivery_user_id_eb6d4217_fk_services_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.services_deliverylog
    ADD CONSTRAINT services_deliverylog_delivery_user_id_eb6d4217_fk_services_ FOREIGN KEY (delivery_user_id) REFERENCES public.services_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: services_deliverylog services_deliverylog_order_id_26f6bb2d_fk_services_order_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.services_deliverylog
    ADD CONSTRAINT services_deliverylog_order_id_26f6bb2d_fk_services_order_id FOREIGN KEY (order_id) REFERENCES public.services_order(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: services_invoice services_invoice_order_id_302c40a1_fk_services_order_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.services_invoice
    ADD CONSTRAINT services_invoice_order_id_302c40a1_fk_services_order_id FOREIGN KEY (order_id) REFERENCES public.services_order(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: services_invoice services_invoice_user_id_7bbf1d33_fk_services_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.services_invoice
    ADD CONSTRAINT services_invoice_user_id_7bbf1d33_fk_services_user_id FOREIGN KEY (user_id) REFERENCES public.services_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: services_invoiceitem services_invoiceitem_invoice_id_1c5e78ec_fk_services_invoice_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.services_invoiceitem
    ADD CONSTRAINT services_invoiceitem_invoice_id_1c5e78ec_fk_services_invoice_id FOREIGN KEY (invoice_id) REFERENCES public.services_invoice(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: services_kitchenlog services_kitchenlog_order_id_45b5526d_fk_services_order_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.services_kitchenlog
    ADD CONSTRAINT services_kitchenlog_order_id_45b5526d_fk_services_order_id FOREIGN KEY (order_id) REFERENCES public.services_order(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: services_order services_order_user_id_2651f880_fk_services_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.services_order
    ADD CONSTRAINT services_order_user_id_2651f880_fk_services_user_id FOREIGN KEY (user_id) REFERENCES public.services_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: services_orderitem services_orderitem_order_id_3d4c1ac5_fk_services_order_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.services_orderitem
    ADD CONSTRAINT services_orderitem_order_id_3d4c1ac5_fk_services_order_id FOREIGN KEY (order_id) REFERENCES public.services_order(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: services_orderitem services_orderitem_product_id_f8c5c801_fk_services_menuitem_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.services_orderitem
    ADD CONSTRAINT services_orderitem_product_id_f8c5c801_fk_services_menuitem_id FOREIGN KEY (product_id) REFERENCES public.services_menuitem(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: services_profile services_profile_user_id_b92023c8_fk_services_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.services_profile
    ADD CONSTRAINT services_profile_user_id_b92023c8_fk_services_user_id FOREIGN KEY (user_id) REFERENCES public.services_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: services_user_groups services_user_groups_group_id_7a938d90_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.services_user_groups
    ADD CONSTRAINT services_user_groups_group_id_7a938d90_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: services_user_groups services_user_groups_user_id_de285bf3_fk_services_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.services_user_groups
    ADD CONSTRAINT services_user_groups_user_id_de285bf3_fk_services_user_id FOREIGN KEY (user_id) REFERENCES public.services_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: services_user_user_permissions services_user_user_p_permission_id_95d2c36c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.services_user_user_permissions
    ADD CONSTRAINT services_user_user_p_permission_id_95d2c36c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: services_user_user_permissions services_user_user_p_user_id_45836c48_fk_services_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.services_user_user_permissions
    ADD CONSTRAINT services_user_user_p_user_id_45836c48_fk_services_ FOREIGN KEY (user_id) REFERENCES public.services_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

