services:
  monolithic-project:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: dev-monolithic-project
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
    networks:
      - core-infrastructure-dev

networks:
  core-infrastructure-dev:
    external: true
