apiVersion: v1
kind: Secret
metadata:
  name: django-app-secret
type: Opaque
stringData:
  DJANGO_SECRET_KEY: "django-insecure-mi-clave-super-secreta"
  POSTGRES_DB: "db"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "password"
  POSTGRES_HOST: "localhost"
  POSTGRES_PORT: "5432"
